# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationcopy',
            name='name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
