# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20170415_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalizepublication',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
