# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_normalizepublication_status'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='normalizepublication',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='normalizepublication',
            name='level',
        ),
        migrations.RemoveField(
            model_name='normalizepublication',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='normalizepublication',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='normalizepublication',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='normalizepublication',
            name='tree_id',
        ),
        migrations.AddField(
            model_name='normalizepublication',
            name='parent_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
