# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20170224_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationnormalized',
            name='PublicationCopy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.PublicationCopy'),
        ),
    ]
