# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 10:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_publicationnormalized_publicationcopy'),
    ]

    operations = [
        migrations.CreateModel(
            name='PubCopyError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
