# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 10:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_pubcopyerror'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PublicationCopy',
            new_name='CopyPublication',
        ),
        migrations.RenameModel(
            old_name='PubCopyError',
            new_name='CopyPublicationError',
        ),
    ]
