# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20170421_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copypublication',
            name='name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
