# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 12:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_copypublicationstatus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PublicationNormalized',
            new_name='NormalizePublication',
        ),
        migrations.RenameField(
            model_name='normalizepublication',
            old_name='PublicationCopy',
            new_name='CopyPublication',
        ),
    ]
