# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ADJS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('name_int', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ADVB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('name_int', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='COMP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('name_int', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CONJ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('name_int', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GRND',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('name_int', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='INFN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('name_int', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='intg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('name_int', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='INTJ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('name_int', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LATN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('name_int', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NPRO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('name_int', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NUMB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('name_int', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NUMR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('name_int', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PNCT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('name_int', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PRCL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('name_int', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PRED',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('name_int', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PREP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('name_int', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PRTF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('name_int', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PRTS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('name_int', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='real',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('name_int', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ROMN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('name_int', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UNKN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('name_int', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VERB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('name_int', models.BigIntegerField()),
            ],
        ),
    ]
