# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0012_auto_20170424_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjf',
            name='Tone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adjs',
            name='Tone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advb',
            name='Tone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comp',
            name='Tone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conj',
            name='Tone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grnd',
            name='Tone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='infn',
            name='Tone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intg',
            name='Tone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intj',
            name='Tone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='latn',
            name='Tone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='noun',
            name='Tone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='npro',
            name='Tone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='numb',
            name='Tone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='numr',
            name='Tone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prcl',
            name='Tone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pred',
            name='Tone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prep',
            name='Tone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prtf',
            name='Tone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prts',
            name='Tone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='real',
            name='Tone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='romn',
            name='Tone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unkn',
            name='Tone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='verb',
            name='Tone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
