# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-04 14:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0015_auto_20170604_1736'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='adjf',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='adjf',
            name='level',
        ),
        migrations.RemoveField(
            model_name='adjf',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='adjf',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='adjf',
            name='tree_id',
        ),
        migrations.AlterField(
            model_name='adjf',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vocabulary.ADJF'),
        ),
    ]
