# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-04 14:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0021_auto_20170604_1744'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='prtf',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='prtf',
            name='level',
        ),
        migrations.RemoveField(
            model_name='prtf',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='prtf',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='prtf',
            name='tree_id',
        ),
    ]
