# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-04 14:50
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0024_auto_20170604_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prts',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vocabulary.PRTS'),
        ),
    ]
