# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-04 14:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0025_auto_20170604_1750'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='grnd',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='grnd',
            name='level',
        ),
        migrations.RemoveField(
            model_name='grnd',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='grnd',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='grnd',
            name='tree_id',
        ),
    ]
