# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-04 14:55
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0029_auto_20170604_1754'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='latn',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='latn',
            name='level',
        ),
        migrations.RemoveField(
            model_name='latn',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='latn',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='latn',
            name='tree_id',
        ),
        migrations.AlterField(
            model_name='latn',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vocabulary.LATN'),
        ),
    ]
