# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-04 15:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0032_auto_20170604_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prts',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vocabulary.PRTS'),
        ),
    ]
