# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-04 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0033_auto_20170604_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='noun',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
