# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 18:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CanonizatorError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(blank=True, max_length=512, null=True)),
                ('error', models.TextField()),
                ('date', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Crawler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=512, null=True)),
                ('file_name', models.CharField(blank=True, max_length=512, null=True)),
                ('imported', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=512, null=True)),
                ('text', models.TextField()),
                ('date', models.DateTimeField(db_index=True)),
                ('author', models.CharField(blank=True, max_length=512, null=True)),
                ('url', models.URLField()),
                ('crawler', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.Crawler')),
            ],
        ),
    ]
