# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawler',
            name='name_cyrillic',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
