# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_crawler_publication'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanonizatorError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(blank=True, max_length=512, null=True)),
                ('error', models.TextField()),
                ('date', models.DateTimeField(db_index=True)),
            ],
        ),
    ]
