# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_canonizatorerror'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='author',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
